### PR TITLE
Add SMART.iX to the production users/companies

### PR DESCRIPTION
**Pull request by marziman**
- Added the logo to assets
- Adjusted the banner with logo

### CODE REVIEW

**Comment by scholzj** [comment]
@marziman Any chance to look at the comment and fix the DCO? Thanks.

**Comment by scholzj** [comment]
I opened a new PR #243 which replaces this one and fixes the design and DCO issues. @marziman please let us know if that is not ok for you. Thanks.

**Comment by marziman** [comment]
Thanks @scholzj I was under water with other topics. Will comment in new PR and it shall be ok

**Comment by scholzj** [comment]
> Thanks @scholzj I was under water with other topics. Will comment in new PR and it shall be ok

No worries, we are glad to have your logo on the website. Thanks.

**Pull request closed without merging**
