### PR TITLE
 Added marlow navigation placement and logo

### PR DESCRIPTION
**Pull request by nmousouros**
We use strimzi in production for our mobile app api and different services

### CODE REVIEW

**Comment by scholzj** [comment]
Could you please try to fix the DCO signoff? It should be the following two commands:

```
git commit --amend --signoff
git push --force-with-lease origin patch-1
```

More details can be found in the PR status section after clicking the _Details_ link net to the DCO status. Thanks a lot.

**Comment by ppatierno** [comment]
@nmousouros and sorry for confusing but logos are not in alphabetical order for now :-( I know I confused you with the adopters file (that is in alphabetical order). We'll make a common decision for this confusion but could you please put the logo at the end please?
Remember to fix your DCO.

**Comment by nmousouros** [comment]
> @nmousouros and sorry for confusing but logos are not in alphabetical order for now :-( I know I confused you with the adopters file (that is in alphabetical order). We'll make a common decision for this confusion but could you please put the logo at the end please?
> Remember to fix your DCO.

No worries you didn't confuse me I did it in a rush without reading your guidelines. Is it ok now?

**Comment by ppatierno** [comment]
@nmousouros ok thanks, we'll arrange the logos maybe differently based on their size.
You should fix DCO and we are good to merge.

**Comment by ppatierno** [comment]
@nmousouros you did new commits without signing so DCO is again red :-( Can you fix this and we are good to merge please?

**Pull request closed without merging**
