### PR TITLE
Add Decathlon Digital to "used by" homepage section

### PR DESCRIPTION
**Pull request by ThomasDangleterre**
### Type of change

_Select the type of your PR_

* [ ] Typo/minor fix
* [ ] New blog post (see the [README](https://github.com/strimzi/strimzi.github.io/#blog-posts) for the process)
* [x] Other

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
Great, thanks a lot.

**Comment by ppatierno** [comment]
@ThomasDangleterre thanks for the PR! I am not a web expert but the preview looks weird. @scholzj any suggestions to have last logos in the middle and not on the sides?

**Comment by ppatierno** [comment]
> It adjusts to the screen size to decide how many logos should be per row etc.

But why on the sides and not in the middle :-(

**Review by ppatierno — APPROVED** [review]
LGTM. Thanks!!!

**Comment by scholzj** [comment]
Maybe @PaulRMellor might have an idea?

**Comment by scholzj** [comment]
I think changing this line: https://github.com/strimzi/strimzi.github.io/blob/b5acaea8b7fab22b5cf54d5360692aa4b7378f73/_sass/strimzi.scss#L25 to justify-content: center will align it to center. We can do it in separate PR.

**Comment by ppatierno** [comment]
@scholzj yeah looks great! Thanks! Going to merge the PR!

**Pull request merged**
