### PR TITLE
Move Strimzi Roadmap to GitHub project

### PR DESCRIPTION
**Pull request by scholzj**
As discussed earlier ... I think the _Roadmap_ page is not well maintained and not easy to read. I tried to create a [GitHub project](https://github.com/strimzi/strimzi-kafka-operator/projects/1) to track the roadmap and the "epics and link to it from strimzi.io. Please let me know what you think.

### CODE REVIEW

**Comment by tombentley** [comment]
:+1: on removing the existing roadmap and linking out to something else.

My main reservation is just that the Github Project looks strange:

* Do we really need to show columns for even very old releases (the columns are wider than my monitor)?
* Wouldn't it be more natural to have the columns in the reverse order (time moves to the right in my mind)?

**Comment by scholzj** [comment]
So where would you put the _To Do_ column? Logically the _To Do_ column should be next to the newest / upcoming release. So would _To Do_ be the most right column?

**Comment by ppatierno** [comment]
@scholzj yes but ... I don't think that it's possible to have the browser opening the roadmap and moving the scroll bar to the right (showing the most recent releases and "to do") so I think that the current layout is better. When the roadmap is opened, the people can see immediately what we are working on (release in process) and the to-do.

**Comment by scholzj** [comment]
I merged this because the roadmap on the website was getting outdated. Any further changes to how the roadmap project looks and what are the columns could be addresses separately.

**Pull request merged**
