### PR TITLE
The company's logos (e.g., Strimzi) now adapt to different screen sizes and are responsive.

### PR DESCRIPTION
**Pull request by UtkarshMishra12**
### Type of change

_Select the type of your PR_ 
Fixes: #388 

* [ ] Typo/minor fix
* [ ] New blog post (see the [README](https://github.com/strimzi/strimzi.github.io/#blog-posts) for the process)
* [x] Other

**The company's logos (e.g., Strimzi) now adapt to different screen sizes and are responsive.**

### CODE REVIEW

**Comment by UtkarshMishra12** [comment]
@scholzj Please review it and share your thoughts 😄

**Review by scholzj — COMMENTED** [review]
I guess the `logo-img` class is not used anymore and can be removed from the styles. 

Also, can we get some more spacing between the logos? On my screen they seem quite tightly together:

Screenshot 2023-09-26 at 22 15 04

**Comment by ppatierno** [comment]
On my screen it looks good ... 

image

... but the space narrow down when I reduce the window. In the end it stacks logo.

**Comment by ppatierno** [comment]
Just adding it works great on mobile.

**Comment by UtkarshMishra12** [comment]
> On my screen it looks good ...
> 
> image
> 
> ... but the space narrow down when I reduce the window. In the end it stacks logo.

@ppatierno What should be my next step? What changes should I make now?

**Comment by ppatierno** [comment]
@UtkarshMishra12 Jakub was asking if the `logo-img` class could be removed now. I am not a CSS expert so I will leave that to you :-)

https://github.com/strimzi/strimzi.github.io/blob/main/_sass/includes/homepage-usedby-band.scss#L6

**Comment by UtkarshMishra12** [comment]
@scholzj I believe we can delete the entire [SCSS file](https://github.com/strimzi/strimzi.github.io/blob/main/_sass/includes/homepage-usedby-band.scss#L1) since the class `homepage-usedby-band` is no longer in use. What's your opinion on this?

**Comment by scholzj** [comment]
@UtkarshMishra12 I'm afraid I have no idea. I noticed about the class from your PR. But I do not know what else is in there. If it is not needed I assume it can be deleted, yes.

**Review by ppatierno — APPROVED** [review]
LGTM. Thanks for the PR!

**Comment by UtkarshMishra12** [comment]
@scholzj @ppatierno Now it's fixed, everything is fine on my end 😃

**Review by scholzj — APPROVED** [review]
LGTM. Thanks.

**Comment by scholzj** [comment]
Thanks a lot for the PR!

**Pull request merged**
