### PR TITLE
MINOR: Adds LittleHorse Logo

### PR DESCRIPTION
**Pull request by coltmcnealy-lh**
### Type of change

* [ ] Other

Adds LittleHorse Logo.

### CODE REVIEW

**Comment by coltmcnealy-lh** [comment]
I unfortunately wasn't able to build either on terminal or via docker image. On the docker image, I got the following error:

```
Use `bundle info [gemname]` to see where a bundled gem is installed.
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
  Liquid Exception: Liquid syntax error (line 8): Unknown tag 'when' in strimzi/bundle/ruby/3.0.0/gems/liquid-4.0.3/lib/liquid/locales/en.yml
                    ------------------------------------------------
      Jekyll 4.2.0   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/usr/gem/gems/liquid-4.0.3/lib/liquid/document.rb:23:in `unknown_tag': Liquid syntax error (line 8): Unknown tag 'when' (Liquid::SyntaxError)
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/document.rb:11:in `block in parse'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:32:in `parse'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/document.rb:10:in `parse'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/document.rb:5:in `parse'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:132:in `parse'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:116:in `parse'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:12:in `parse'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:126:in `render_liquid'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:80:in `render_document'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:63:in `run'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:547:in `render_regenerated'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:539:in `block in render_pages'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:538:in `each'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:538:in `render_pages'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:211:in `render'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:80:in `process'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /usr/gem/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:29:in `load'
	from /usr/local/bundle/bin/jekyll:29:in `<main>'
```

I will debug more tonight.

**Comment by ppatierno** [comment]
@coltmcnealy-lh could you fix the DCO as well please?
Btw the Netlify preview seems to be fine.

**Review by scholzj — APPROVED** [review]
Netlify builds a preview. |ou can see it here: https://deploy-preview-390--strimzi.netlify.app/ ... I think it looks good. Thanks.

**Comment by coltmcnealy-lh** [comment]
The preview on Netlify looks good to me, and I think I figured out the DCO thing. Thanks both of you!

**Review by ppatierno — APPROVED** [review]
LGTM. Thanks!

**Comment by scholzj** [comment]
Thnks @coltmcnealy-lh

**Pull request merged**
