### PR TITLE
docs(web pages): updates to the ToC and general navigation improvements

### PR DESCRIPTION
**Pull request by PaulRMellor**
**Updates to doc web pages**

- Removes the resizeable ToC
- Adds a new ToC switch to turn the ToC on/off
- Reduces the size of the ToC text to put more titles on a single line
- Adds a dynamic "Top" button (mainly for mobile views to return to the ToC)
- Sets a more readable weight to the text

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
Nice work. Thanks.

**Review by fvaleri — APPROVED** [review]
This is much better IMO, and there is no delay on window resize. Thanks!

**Review by ppatierno — APPROVED** [review]
Nice work Paul! Just saying that on my side, if you make the browser window smaller or you use a mobile phone, the TOC cannot be disabled but just stay at the top of the page as before. Is it normal?

**Comment by PaulRMellor** [comment]
> Nice work Paul! Just saying that on my side, if you make the browser window smaller or you use a mobile phone, the TOC cannot be disabled but just stay at the top of the page as before. Is it normal?

Thanks Paolo. At smaller widths the side ToC disappears because of the width restrictions and you get the ToC (a different one) at the top. It's always been like that, and as it doesn't get in the way of the text there's no point in removing it like the side ToC. But the new "Top" button lets you go straight back to the top to see it again.

**Pull request merged**
