### PR TITLE
Update homepage-usedby-band.html

### PR DESCRIPTION
**Pull request by tym83**
Cozystack and Aenix logo added

### Type of change

_Select the type of your PR_

* [ ] Typo/minor fix
* [ ] New blog post (see the [README](https://github.com/strimzi/strimzi.github.io/#blog-posts) for the process)
* [x] Other

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Thanks for the PR. I left one comment.

**Review by tym83 — COMMENTED** [review]
Fix added

**Comment by ppatierno** [comment]
@tym83 thanks for the PR! Now that we have the logs in (I merged the other two PRs) could you rebase this one so that we have the preview by netlify with logos as well please?
With just this PR (not rebased) this is what we have in the preview ...

image

which is not that great. Thanks!

**Review by ppatierno — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
